name: Go

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        cd test
        go mod init "github.com/IgnacioARD/test"
      
    - name: Tidy
      run: |
        cd test
        go mod tidy

    - name: Test
      run: |
        cd test
        go test -v
        
