name: Go

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Change dicrectory
      run: cd test

    - name: Build
      run: go mod init "github.com/IgnacioARD/test"
      
    - name: Tidy
      run: go mod tidy

    - name: Test
      run: go test -v ../
